pycbc:
  seobnrv4:
    waveform_name:   "SEOBNRv4"
    delta_t:         2056
    f_lower:         20.0
    detector_name:   "H1"
    waveform_length: 2056

  phenomd:
    waveform_name:   "IMRPhenomD"
    delta_t:         2056
    f_lower:         20.0
    detector_name:   "H1"
    waveform_length: 2056

model:
  amp_emb_hidden: [64,64]
  amp_hidden: [128,128,128]
  amp_banks: 1
  amp_dropout: 0.1
  amp_lr: 0.0009
  amp_clip: 3
  phase_emb_hidden: [64,64]
  phase_hidden: [256,256,256,256, 256]
  phase_banks: 6
  phase_dropout: 0.1
  phase_lr: 0.0007
  phase_clip: 4

sampling_ranges:
  mass_min:     50.0
  mass_max:     100.0
  spin_mag_min: -0.7
  spin_mag_max:  0.7
  incl_min:      0.0
  incl_max:      3.141592653589793
  ecc_min:       0.0
  ecc_max:       0.3
  clean:         True # clean or noisy data
  snr_min:       10
  snr_max:       20

training:
  # Data & splitting
  num_samples:    1000
  val_split:      0.3
  random_seed:    42

  # Optimization
  optimizer:      "adam"
  learning_rate:  0.005
  weight_decay:   0.1

  # Batching & epochs
  batch_size:     8192
  num_epochs:     200
  patience:       50
  min_delta:      1e-6
  gradient_clip:  1.0

  # Scheduler
  scheduler:
    lr_decay_factor: 0.5
    lr_patience:     10
    min_lr:          1e-6

  # Hyperparameter search
  hpo:
    n_trials:       50
    sampler:        "tpe"
    timeout:        null

  # Misc
  seed_everything: true

device: "cuda"

notifications:
  webhook_url: 0
  discord_bot_token: ""
  status_channel_id: 0
  guild_id: 0

paths:
  checkpoint_dir: "checkpoints"
