pycbc:
  seobnrv4:
    waveform_name:   "SEOBNRv4"
    delta_t:         2048
    f_lower:         20.0
    detector_name:   "H1"
    waveform_length: 2048

  phenomd:
    waveform_name:   "IMRPhenomPv2"
    delta_t:         2048
    f_lower:         20.0
    detector_name:   "H1"
    waveform_length: 16384

model:
  amp_emb_hidden: [64,64]
  amp_hidden: [128,128,128]
  amp_banks: 2
  phase_emb_hidden: [64,64]
  phase_hidden: [128,128,128,128]
  phase_banks: 2

sampling_ranges:
  mass_min:     20.0
  mass_max:     50.0
  spin_mag_min: -0.99
  spin_mag_max:  0.99
  incl_min:      0.0
  incl_max:      3.141592653589793
  ecc_min:       0.0
  ecc_max:       0.3
  clean:         True # clean or noisy data
  snr_min:       10
  snr_max:       20

training:
  # Data & splitting
  num_samples:    10
  val_split:      0.3
  random_seed:    42

  # Optimization
  optimizer:      "adam"
  learning_rate:  0.001
  weight_decay:   0.0

  # Batching & epochs
  batch_size:     256
  num_epochs:     200
  patience:       50
  min_delta:      1e-6
  gradient_clip:  1.0

  # Scheduler
  scheduler:
    lr_decay_factor: 0.5
    lr_patience:     10
    min_lr:          1e-6

  # Fine‑tuning
  fine_tune:
    enable:         true
    epochs:         50
    learning_rate:  0.0001

  # Hyperparameter search
  hpo:
    n_trials:       50
    sampler:        "tpe"
    timeout:        null

  # Misc
  seed_everything: true

device: "cuda"

notifications:
  webhook_url:  
    "https://discord.com/api/webhooks/1392085647480721428/wDGdLRmMXrStJXhobZTjkAa4SrW35BKoRTMcdLKBFDdq-qiECTjD-2SYLa4cLL3ZU2Bx"
  discord_bot_token: "MTM5MjE0MDE1ODg1NzUxNTAxOA.GPDujQ.yM-i8yzG-p6tV0LrvpyoBdjvEjNGUgKq1LdX0U"
  status_channel_id: 1392085614375206932
  guild_id: 1392085562323636348

paths:
  checkpoint_dir: "checkpoints"
