pycbc:
  waveform_name: "IMRPhenomXPHM"
  delta_t: 0.0001220703125    # 1/8192
  f_lower: 20.0
  detector_name: "H1"
  psi_fixed: 0.0

time_window:
  t_before: 4.0
  t_after: 1.0

sampling_ranges:
  mass_min: 5.0
  mass_max: 50.0
  spin_mag_min: 0.0
  spin_mag_max: 0.99
  incl_min: 0.0
  incl_max: 3.141592653589793
  ecc_min: 0.0
  ecc_max: 0.3
  ra_min: 0.0
  ra_max: 6.283185307179586
  dec_min: -1.5707963267948966
  dec_max: 1.5707963267948966
  dist_min: 10.0
  dist_max: 2000.0
  coal_min: -0.5
  coal_max: 0.5

training:
  num_samples: 10
  batch_size: 64
  num_epochs: 200
  learning_rate: 0.001
  patience: 10
  fine_tune_epochs: 30
  fine_tune_lr: 0.0001

device: "cuda"

paths:
  checkpoint_dir: "checkpoints"
