pycbc:
  waveform_name: "SEOBNRv4"
  delta_t: 0.00024414062   # 1/4096
  f_lower: 20.0
  detector_name: "H1"
  waveform_length: 1024

sampling_ranges:
  mass_min: 20.0
  mass_max: 50.0
  spin_mag_min: -0.99
  spin_mag_max: 0.99
  incl_min: 0.0
  incl_max: 3.141592653589793
  ecc_min: 0.0
  ecc_max: 0.3

training:
  num_samples: 10
  batch_size: 256
  num_epochs: 100
  learning_rate: 0.001
  patience: 50
  fine_tune_epochs: 50
  fine_tune_lr: 0.0001

device: "cuda"

paths:
  checkpoint_dir: "checkpoints"
